on:
    push:
      branches: [main]

jobs:
    deploy-frontend:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: your-firebase-project-id

    deploy-backend:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: "your-heroku-app-name"
        if: success()
        run: |
          heroku container:login
          heroku container:push web -a $HEROKU_APP_NAME
          heroku container:release web -a $HEROKU_APP_NAME