name: Frontend CI

on:
  push:
    paths:
      - 'frontend-angular/**'
  pull_request:
    paths:
      - 'frontend-angular/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend-angular

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: frontend-angular/package-lock.json

    - name: Install Dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Build
      run: npm run build

    - name: Run Tests
      run: npm test